### ISSUE TITLE
geo_type polygon

### ISSUE THREAD

**Issue by Farkal** [Stoeoef/rstar#10]
Hi, 
Thanks for your great work.

I have a list of geo_type [Polygon](https://docs.rs/geo-types/0.4.3/geo_types/struct.Polygon.html) and would like to insert them in rtree. Actually I am obliged to convert each segment in Line and link properties of the polygon by index.
Is there an easier way ?

**Comment by urschrei** [comment]
The easiest way (i.e. what we do in `Geo`), is something like

    use geo_types::{Line, Polygon}
    use rstar::RTree;
    // create polygon here, e.g. let poly = …

    let tree: RTree<Line<_>> = RTree::bulk_load(poly.lines().collect::<Vec<_>>());`

Note that this will only give you an RTree of the exterior ring. If you need interior rings in the tree you'll have to collect the line segments separately, append that vector to the ring vector, and pass the combined vector to `bulk_load`.

**Comment by Farkal** [comment]
It's say the trait is not implemented.

My code: (add .exterior(), lines() method is unknown on polygon)
```
use geo_types::{Line, Polygon, LineString};
use rstar::RTree;
let polygon = Polygon::new(LineString::from(vec![
                (0., 0.),
                (1., 1.),
                (1., 0.),
                (0., 0.),
            ]), vec![]);

let tree: RTree<Line<_>> = RTree::bulk_load(polygon.exterior().lines().collect::<Vec<_>>());
```

The error:
```
the trait bound `geo_types::line::Line<_>: rstar::point::Point` is not satisfied

the trait `rstar::point::Point` is not implemented for `geo_types::line::Line<_>`

note: required because of the requirements on the impl of `rstar::object::RTreeObject` for `geo_types::line::Line<_>`
note: required by `rstar::rtree::RTree`rustc(E0277)
```

**Comment by urschrei** [comment]
Ah, we're still using 0.2.0…

**Comment by Stoeoef** [comment]
The above error could indeed be related to a version mismatch. Does downgrading rstar to 0.2.0 solve this? If you are using only geo-types, you may need to enable the `rstar` feature like this in your cargo.toml:

`geo-types = { version = "0.4", features = ["rstar"] }`

At least the [`impl` for `Line`](https://github.com/georust/geo/blob/21dbed14d46310beef3d1c83410677840163b903/geo-types/src/line.rs#L163) seems to be feature gated.

Also, to address your original problem, it may be easier to implement `RTreeObject` directly for `Polygon`. This would make it unnecessary to track which line belongs to which polygon but may be slow for large polygons. [This PR](https://github.com/georust/geo/pull/351/commits/2b702bce790d918e09dbc6cb4f244312636a87b5) does that, although it does not seem to consider any interior rings.

Since you can't write the `impl` outside of `geo-types`, you will need to create a new type containing the polygon.

**Comment by Farkal** [comment]
That's what I have done, I created new type for my polygon, here is the code:

```rust
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct FloatPoint2D
{
    pub x: f64,
    pub y: f64
}

impl Point for FloatPoint2D
{
  type Scalar = f64;
  const DIMENSIONS: usize = 2;

  fn generate(generator: impl Fn(usize) -> Self::Scalar) -> Self
  {
    FloatPoint2D {
      x: generator(0),
      y: generator(1)
    }
  }

  fn nth(&self, index: usize) -> Self::Scalar
  {
    match index {
      0 => self.x,
      1 => self.y,
      _ => unreachable!()
    }
  }
   
  fn nth_mut(&mut self, index: usize) -> &mut Self::Scalar
  {
    match index {
      0 => &mut self.x,
      1 => &mut self.y,
      _ => unreachable!()
    }
  }
}

#[derive(Debug)]
pub struct FeaturePolygon
{
    pub polygon: Vec<FloatPoint2D>,
    pub feature: HashMap<String, FieldValue>
}

impl RTreeObject for FeaturePolygon
{
    type Envelope = AABB<[f64; 2]>;

    fn envelope(&self) -> Self::Envelope
    {
        // Create rectangle from polygon min max
        let min_x = self.polygon.iter().ord_subset_min_by_key(|p| p.x).unwrap().x;
        let max_x = self.polygon.iter().ord_subset_max_by_key(|p| p.x).unwrap().x;
        let min_y = self.polygon.iter().ord_subset_min_by_key(|p| p.y).unwrap().y;
        let max_y = self.polygon.iter().ord_subset_max_by_key(|p| p.y).unwrap().y;
        AABB::from_corners([min_x, min_y], [max_x, max_y])
    }
}
```

It's not really optimized because it create a square from the polygon extremities so a point can be inside the square but outside the polygon. If you have better solution please tell me 😉

**Comment by Stoeoef** [comment]
A simple yet very effective optimization would be to store the AABB instead of recalculating it everytime the AABB is queried. If performance is a bottleneck, that would be my first step. Inserting will be as fast as inserting regular rectangles then.

Also, instead of implementing your own point, I would probably consider using `[f64; 2]`, which requires less boilerplate.

Which kind of queries do you need to run once the r-tree is constructed? Nearest neighbor queries? Point-in-Polygon queries? For the first one, you will need to implement `PointDistance`, for the latter, specialising the [PointDistance::ContainsPoint](https://docs.rs/rstar/0.4.0/rstar/trait.PointDistance.html#method.contains_point) method might be appropriate.

**Comment by Farkal** [comment]
Ok thank's your advices.
I load all my geometries with `bulk_load` and only use `locate_in_envelope_intersecting` or `locate_in_envelope` to find which polygon are inside some area.

**Comment by Stoeoef** [comment]
If `locate_in_envelope` / `locate_in_envelope_intersecting` are the only functions you require, pre-computing the AABB is the way to go. Essentially, you are reducing polygons to their AABB, just as if inserting rectangles.
Let me know if there is anything to add or if I can close the issue!
