### ISSUE TITLE
Implementation advice: Custom RTreeObjects which do not implement Copy nor Clone

### ISSUE THREAD

**Issue by liona24** [Stoeoef/rstar#19]
Hey,

I am currently facing some issues while trying to use this crate with custom objects. 

What I am trying to do, is some kind of lazy removal. Take a look at the example code below:
```rust
use rstar::{RTree, RTreeObject, AABB, PointDistance};

#[derive(PartialEq)]
struct Element {
    is_valid : bool,
    position : [f32; 2],
    // ..
}

impl RTreeObject for Element {
    type Envelope = AABB<[f32; 2]>;

    fn envelope(&self) -> Self::Envelope {
        AABB::from_point(self.position)
    }
}

impl PointDistance for Element {
    fn distance_2(&self, point : &[f32; 2]) -> f32 {
        let dx = self.position[0] - point[0];
        let dy = self.position[1] - point[1];

        dx * dx + dy * dy
    }
}

fn main() {
    let mut tree = RTree::new();

    {
        tree.insert(Element { is_valid : true, position: [0.0, 0.2] });
        tree.insert(Element { is_valid : false, position: [1.0, 0.2] });
    }

    while let Some(el) = tree.nearest_neighbor(&[1.0, 2.0]) {
        if !el.is_valid {
            // Compiler error here: Borrow twice
            tree.remove(el);
        } else {
            // ..
            break;
        }
    }
}
```

Essentially the problem is that the tree owns all the data, so I cannot back-reference the objects in the tree and therefor cannot remove any elements in the tree.

Implementing Copy or Clone is not feasible as the objects I want to store could be quite large. A possible workaround is to simply insert `Rc<RefCell<Something>>` into the tree and make the data owned by something else, though this is very verbose.

What I imagine a nice(r) solution would be something like `pop_nearest` or so.

**Comment by Stoeoef** [comment]
That's a fair question, I believe that use case is actually not properly supported at the moment.

Implementation wise, doing what you want should be easy. Internally, the element that should be removed is found with a [`SelectionFunction`](https://docs.rs/rstar/0.6.0/rstar/trait.SelectionFunction.html), ([sourcecode](https://github.com/Stoeoef/rstar/blob/master/rstar/src/algorithm/removal.rs)), which can be designed specifically to point to the nearest neighbor by searching for its address:

```rust
struct ByAddressSelectionFunction<T> where T: RTreeObject {
    envelope: T::Envelope,
    element_address: *const T,
}

impl <T> SelectionFunction<T> for ByAddressSelectionFunction<T> where T: RTreeObject {
   fn should_unpack_parent(&self, parent_envelope: &T::Envelope) -> bool {
        parent_envelope.contains_envelope(&self.envelope)
    }

    fn should_unpack_leaf(&self, leaf: &T) -> bool {
        std::ptr::eq(self.element_address, leaf)
    }
}
```
-------------------------------------------------

The remove method above is not public though. That's why a change to rstar will be required, e.g. adding a `RTree::remove_with_selection_function` like this:

```rust
    pub fn remove_with_selection_function(&mut self, removal_function: &impl SelectionFunction<T>) 
    -> Option<T> {
        let result = removal::remove::<_, Params, _>(&mut self.root, removal_function);
        if result.is_some() {
            self.size -= 1;
        }
        result
    }
```
The main loop then becomes:

```rust
        while let Some(nearest) = tree.nearest_neighbor(&[0.0f32, 0.0]) {
            let removal_function = super::ByAddressSelectionFunction {
                envelope: nearest.envelope(),
                element_address: nearest,
            };
            tree.remove_with_selection_function(&removal_function);
        }
```
---------------------------------------------------

Ah, well. Now I've coded most of this already. Would this solve your problem? If so and you are in a hurry, please let me know and feel free to open a pull request. Otherwise, I should find some time to do this soon™.

Adding a "pop_nearest" (or "pop_closest"?) sounds like a decent addition. Internally I would implement it just like above.

**Comment by liona24** [comment]
I guess this would be a perfectly fine solution for me, though I just went with `Rc<RefCell<..>>` - approach for now. 

But I can certainly take a closer look tomorrow.

**Comment by Stoeoef** [comment]
0.7.0 is now up and running, containing the new method!
Closing.
