### ISSUE TITLE
Unreachable! panic when inserting points

### ISSUE THREAD

**Issue by alec-deason** [Stoeoef/rstar#45]
I'm seeing unreachable! panics when I insert certain configurations of points. An example which reproducibly fails for me is here: https://gist.github.com/alec-deason/6218fb2fd6262bdd63473e417e050004

I've stripped that down so that changing the position of any of the last few points even slightly will flip it from failing to succeeding. Adding or removing any points either from the bulk loaded set or the ones that are inserted later makes the failure go away. Also inserting all of he points one at a time rather than bulk loading the initial set causes the failure to go away in this example, though I haven't experimented enough to see if the failure only appears with bulk loading.

The program that generated this list of points hits this failure case regularly but not with every set it generates. I have seen it hit the unreachable! panic in both algorithm::rstar::forced_insertion and algorithm::rstar::recursive_insert, which look to be the same underlying failure.

I'm using nightly. I see the same behavior with rstar 0.8.1 and with the latest commits.

**Comment by alec-deason** [comment]
After further experimentation, this does seems to only happen when bulk loading points.

**Comment by Stoeoef** [comment]
Thanks a lot for the report!

After some digging, the bug results from a flaw in the implementation of the reinsert logic.

The bug happens if multiple reinserted elements cause a root node split. The current implementation will split the root twice, leading to a node of too small size which is not the root node, causing follow up bugs.

While using `bulk_load` is not required to cause this issue, it may increase the likelihood of running into this. The error will be much more likely to happen for smaller trees than for larger trees as the likelihood of a split occurring when inserting the nth element is roughly proportional to e^-n.

Thanks again for the report! I've published version 8.2 containing the fix.

**Comment by alec-deason** [comment]
Awesome. Thanks for maintaining this very useful library.
