### ISSUE TITLE
Expose RTreeNode as public?

### ISSUE THREAD

**Issue by jagill** [Stoeoef/rstar#6]
I'd like to check for all intersections between two RTrees.  The most efficient way to do this is to recurse down the nodes, checking the envelopes along the way.  However, RTreeNode (and related structs) is in structures::node, which isn't public (although structures::aabb is).  Could we expose structures::node in lib.rs like we do aabb?  Happy to write the (very small) PR if that helps.

**Comment by Stoeoef** [comment]
Thanks for pointing this out! This seems indeed like a good use case to support.
I am hesitant to expose `RTreeNode` and `ParentNodeData` at the moment as I don't think they are stable enough for a public interface. However, for the rtree-demo, which visualizes the tree, I needed access to the tree's structure and added the (undocumented) `debug` feature which exposes `RTreeNode`. This may also help in your situation but - as I said - this was never meant to be part of a public interface.

So, in order to quickly solve your problem, enabling the "debug" feature may already sufficient for you. For a _sound_ solution, I would prefer an API design that does not expose too many internal parts, although I'm yet unsure how this would look like. If `RTreeNode` is exposed, this will at least require to make all fields and some methods pub(crate).

Does enabling the `debug` feature work for you?
As an added bonus, I could get rid of the hidden "debug" feature.

**Comment by jagill** [comment]
I like the current enum structure of RTreeNode, and agree that ParentNodeData is still a little raw.  I'd image a ParentNode struct that would support something like the following algorithm:

```rust
pub fn intersection_candidates<'a, T: RTreeObject>(
    tree1: &'a RTree<T>,
    tree2: &'a RTree<T>,
) -> Vec<(&'a T, &'a T)> {
    _intersection_candidates(tree1.root(), tree2.root())
}

fn _intersection_candidates<'a, T: RTreeObject>(
    node1: &'a RTreeNode,
    node2: &'a RTreeNode,
) -> Vec<(&'a T, &'a T)> {
    let mut candidates = Vec::new();
    if !node1.envelope().intersects(node2.envelope()) {
        return candidates;
    }
    match (node1, node2) {
        (Leaf(t1), Leaf(t2)) => candidates.push((t1, t2)),
        (Leaf(t), Parent(p)) | (Parent(p), Leaf(t)) => {
            for child in p.children() {
                candidates.extend(_intersection_candidates(t, p))
            }
        }
        (Parent(p1), Parent(p2)) => {
            for child1 in p1.children() {
                if child1.envelope().intersects(p2.envelope()) {
                    for child2 in p2.children() {
                        candidates.extend(_intersection_candidates(child1, child2))
                    }
                }
            }
        }
    }
    candidates
}
```

I think ParentNodeData is really close; we can rename it to ParentNode, expose children as a function, and hide the various scary internal methods as non-public.  This wouldn't allow custom building yet, but it will allow custom querying.

**Comment by Stoeoef** [comment]
Looks good to me!
I also considered renaming `ParentNodeData` to `ParentNode`.
In regards to exposed functions, `children(&self) -> Vec` and `envelope(&self) -> AABB` would be the only things to be included in the public interface. Have you already started doing some implementation work there?  Otherwise, I should find some time to tackle this, just let me know.

**Comment by Stoeoef** [comment]
Should be fixed with 5baf2ea81fd00d09497f1bba6571aec0ffeaed9a . _Note_: I also added the method `RTree::intersection_candidates_with_other_tree` which returns an iterator that just does what you need. I believe that is a fine method to be implemented on R-Trees.

**Comment by Stoeoef** [comment]
This is part of 0.3.0 - thanks again for the idea.

**Comment by jagill** [comment]
This works great, thanks!

I took a stab at doing this, but realized I'd need to understand the insertion strategy more than I did to not mess it up :).  Thanks for the quick improvement!
