### ISSUE TITLE
Add a `RTree::locate_in_circle` method

### ISSUE THREAD

**Issue by varkor** [Stoeoef/rstar#9]
Analogous to [`RTree::lookup_in_circle`](https://docs.rs/spade/1.7.0/spade/rtree/struct.RTree.html#method.lookup_in_circle). At the moment, as far as I can tell, I have to use `locate_in_envelope_intersecting` and then repeatedly check to see whether the item is further away than the radius using `distance_2`.

**Comment by Stoeoef** [comment]
Does `RTree::nearest_neighbor_iter().filter(filter_fn)` solve your problem? This may be more efficient than using `locate_in_envelope`. I'm a bit hesitant to add `lookup_in_circle`, as it is not clear by its name if the returned items need to be fully contained within the circle or if a partial intersection is enough.

**Comment by varkor** [comment]
> Does `RTree::nearest_neighbor_iter().filter(filter_fn)` solve your problem?

This was the other thing I thought of using, though it still requires recomputing the distance. Might there be a way to return an iterator of `(distance, object)` pairs?

> it is not clear by its name if the returned items need to be fully contained within the circle

I would imagine partial intersection would be the sensible choice if you were to add it, as when the radius is zero, it should coïncide with `locate_all_at_point`.

**Comment by Stoeoef** [comment]
I didn't think about the distance which needs to be recreated! Offering an iterator that includes this distance seems like a decent addition. However, since this iterator needs to return the objects sorted by distance there would be still some overhead I believe.

Thus, I like the `lookup_in_circle` functionality, just not its name -  how about `locate_within_distance2`, or `locate_with_maximum_distance2`? Do you think that solves the ambiguity? This method would only be implemented for `RTreeObjects` with the `PointDistance` trait.

> I would imagine partial intersection would be the sensible choice if you were to add it, as when the radius is zero, it should coïncide with locate_all_at_point.

I believe I could write and name 3 different methods:
1. `locate_within_distance`, which uses the `PointDistance` trait and returns all objects with a distance smaller than a certain value. This can be implemented more efficient than the iterator I believe. 
2. `locate_in_circle`, which would not use the `PointDistance` but merely return any object whose _envelope_ is fully contained within the given circle
3. `locate_in_circle_intersecting` which is the same as 2., but returns any object whose envelope intersects the given circle.

"2." may overlook some objects that are (geometrically) fully contained in the given circle, which sounds like it may be used easily in a wrong way.
"3." seems to offer useful functionality, I'm just not happy with the name... it is still not clear that it is _not_ performing _geometric_ intersections.
"1." sounds like the best solution for me, the only trade off is that a user is required to implement `PointDistance`. However, most

**Comment by Stoeoef** [comment]
Fixed with d280567 . As a nice next step, modifying the new LocateWithinDistance iterator and the NearestNeighborIterator to return a tuple of object and distance might be a good addition. Feel free to open an issue in this regard.

**Comment by varkor** [comment]
Thank you! Could you publish version 0.4 on crates.io?

**Comment by Stoeoef** [comment]
Done!
Version [0.4.0](https://github.com/Stoeoef/rstar/releases/tag/0.4.0) was published.
